finish reorganisation implement better comptime configuration & target handling adjust build script

diff --git a/build b/build
--- a/build
+++ b/build
@@ -5,18 +5,14 @@ SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
 readonly SCRIPT_DIR
 readonly HBC_COMMIT="18e8a831"
 readonly SRC_DIR="$SCRIPT_DIR/src"
-readonly DEFAULT_OUT="$SCRIPT_DIR/target/lily"
 readonly BUILD_PATH="$SCRIPT_DIR/target/build"
 readonly CHECKSUM_FILE="$BUILD_PATH/checksum"
-readonly CONFIG_FILE="$SRC_DIR/lib/target/config.hb"
 
 hbc_flags="--backend-flags=opt_level=speed"
 linker=""
-target="c_native"
+target="default"
 run=0
-debug="false"
 dump_asm=0
-out="$DEFAULT_OUT"
 
 die() {
     printf "ERROR: %s\n" "$1" >&2
@@ -46,9 +42,9 @@ check_hbc() {
 
 check_changes() {
     [ -r "$CHECKSUM_FILE" ] && previous_checksum=$(cat "$CHECKSUM_FILE")
-    current_checksum=$(printf "%s%s%s%s%s" \
+    current_checksum=$(printf "%s%s%s" \
         "$(find "$SRC_DIR" -type f -exec md5sum {} + | sort | md5sum)" \
-        "$linker" "$out" "$target" "$debug" | md5sum)
+        "$linker" "$target" | md5sum)
     echo "$current_checksum" >"$CHECKSUM_FILE"
     [ "${previous_checksum:-}" != "$current_checksum" ]
 }
@@ -59,45 +55,28 @@ parse_args() {
         -h | --help)
             cat <<EOF
 Usage: $0 [options]
-    -r, --run               Run the compiled output (Available only on target=c_native)
-    -d, --debug             Enable debug mode in compilation
-    -a, --dump-asm          Dump the assembly to stdout (Available on all targets)
-    -l, --linker <linker>   Specify linker (Available only on target=c_native)
-    -t, --target <target>   Specify target (Run without <target> to see options)
-    -o, --out <path>        Set output path
+    -r, --run               Run the output binary
+    -a, --dump-asm          Dump the assembly to stdout
+    -l, --linker <linker>   Specify linker
+    -t, --target <target>   Specify target triple (or an alias: 'libc' 'ableos' 'hbvm')
     -h, --help              Show this help message
 Examples:
-    $0 -t hbvm_ableos
-    $0 -r -l 'zig cc' -t c_native
-    $0 -r --debug
-    $0 -a -t hbvm_ableos > out.hbf
+    $0 -t ableos
+    $0 -r -l 'zig cc' -t libc
+    $0 -a -t ableos > out.hbf
 EOF
             exit
             ;;
         -r | --run) run=1 ;;
         -a | --dump-asm) dump_asm=1 ;;
-        -d | --debug) debug="true" ;;
         -t | --target)
-            [ -z "${2:-}" ] &&
-                {
-                    cat <<EOF
-Usage: $0 --target <target>
-    hbvm_ableos             Build for AbleOS
-    c_native                Build for your machine
-EOF
-                    exit
-                }
+            [ -z "${2:-}" ] && die "'--target' requires a non-empty option argument"
             target=$2
             shift
             ;;
         --target=?*) target=${1#*=} ;;
         --target=)
-            cat <<EOF
-Usage: $0 --target <target>
-    hbvm_ableos             Build for AbleOS
-    c_native                Build for your machine
-EOF
-            exit
+            die "'--target' requires a non-empty option argument"
             ;;
         -l | --linker)
             [ -z "${2:-}" ] && die "'--linker' requires a non-empty option argument"
@@ -122,58 +101,58 @@ EOF
         esac
         shift
     done
-
-    if [ -n "$linker" ] && [ "$target" = "hbvm_ableos" ]; then
-        die "Linker cannot be set with target 'hbvm_ableos'"
-    fi
-    if [ "$run" = 1 ] && [ "$target" = "hbvm_ableos" ]; then
-        die "./build does not support running the executable with target 'hbvm_ableos'"
-    fi
-    if [ "$run" = 1 ] && [ "$dump_asm" = 1 ]; then
-        die "Argument '--run' is incompatible with argument '--dump-asm'"
-    fi
+    case $target in
+    hbvm | ableos)
+        if [ $run = 1 ]; then die "'--run' cannot be set with '--target $target'"; fi
+        target="unknown-virt-unknown"
+        ;;
+    libc) target="default" ;;
+    esac
 }
 
-build_c_native() {
-    if [ -z "$linker" ]; then
-        for cmd in "zig cc" clang gcc; do
-            if command -v "${cmd%% *}" >/dev/null 2>&1; then
-                linker=$cmd
-                break
+build() {
+    if check_changes || [ ! -e "$BUILD_PATH/$target/lily" ]; then
+        if [ "$target" = "unknown-virt-unknown" ]; then
+            out="$BUILD_PATH/$target/lily.axe"
+            if [ $dump_asm = 1 ]; then
+                hbc_flags="$hbc_flags --dump-asm"
+                out="/dev/stdout"
             fi
-        done
-        [ -z "$linker" ] && die "Could not find zig, clang, or gcc. Please install any, or add to PATH."
+            mkdir -p "$BUILD_PATH/$target" || die "Failed to create build directory"
+            [ -w "$BUILD_PATH/$target" ] || die "$BUILD_PATH/$target is not writable"
+            hbc "$SCRIPT_DIR/src/main.hb" $hbc_flags "--target=unknown-virt-unknown" >"$out" ||
+                {
+                    rm -f "$BUILD_PATH/$target/lily"
+                    rm -f "$CHECKSUM_FILE"
+                    die "Compilation failed"
+                }
+        else
+            if [ -z "$linker" ]; then
+                for cmd in "zig cc" clang gcc; do
+                    if command -v "${cmd%% *}" >/dev/null 2>&1; then
+                        linker=$cmd
+                        break
+                    fi
+                done
+                [ -z "$linker" ] && die "Could not find zig, clang, or gcc. Please install any, or add to PATH."
+            fi
+            if [ ! "$target" = "default" ]; then
+                hbc_flags="$hbc_flags --target=$target"
+            fi
+            mkdir -p "$BUILD_PATH/$target" || die "Failed to create build directory"
+            [ -w "$BUILD_PATH/$target" ] || die "$BUILD_PATH/$target is not writable"
+            hbc "$SCRIPT_DIR/src/main.hb" $hbc_flags >"$BUILD_PATH/$target/lily.o" ||
+                {
+                    rm -f "$BUILD_PATH/$target/lily.o"
+                    rm -f "$CHECKSUM_FILE"
+                    die "Compilation failed"
+                }
+            $linker "$BUILD_PATH/$target/lily.o" -o "$BUILD_PATH/$target/lily"
+        fi
     fi
-
-    if check_changes || [ ! -e "$out" ]; then
-        hbc "$SCRIPT_DIR/src/main.hb" $hbc_flags >"$BUILD_PATH/out.o" ||
-            {
-                rm -f "$BUILD_PATH/out.o"
-                rm -f "$CHECKSUM_FILE"
-                die "Compilation failed"
-            }
-
-        $linker "$BUILD_PATH/out.o" -o "$out"
-        strip -s "$out" || die "Stripping failed"
-    fi
-
-    if [ "$run" = 1 ]; then exec "$out"; fi
-    if [ "$dump_asm" = 1 ]; then objdump -d "$BUILD_PATH/out.o"; fi
-}
-
-build_hbvm() {
-    [ "$out" = "$DEFAULT_OUT" ] && out="$SCRIPT_DIR/target/lily.axe"
-    hbc_flags="$hbc_flags --target=unknown-virt-unknown"
-    if [ "$dump_asm" = 1 ]; then
-        hbc_flags="$hbc_flags --dump-asm"
-        out=/dev/stdout
-    fi
-    if check_changes || [ ! -w "$out" ]; then
-        hbc "$SCRIPT_DIR/src/main.hb" $hbc_flags >"$out" ||
-            {
-                rm -f "$CHECKSUM_FILE"
-                die "Compilation failed"
-            }
+    if [ ! "$target" = "unknown-virt-unknown" ]; then
+        if [ "$run" = 1 ]; then exec "$BUILD_PATH/$target/lily"; fi
+        if [ "$dump_asm" = 1 ]; then objdump -d "$BUILD_PATH/$target/lily.o"; fi
     fi
 }
 
@@ -182,17 +161,9 @@ main() {
 
     mkdir -p "$BUILD_PATH" || die "Failed to create build directory"
     [ -w "$BUILD_PATH" ] || die "$BUILD_PATH is not writable"
-    [ -w "$(dirname "$out")" ] || die "Out directory does not exist or is not writeable"
 
-    printf "target := @use(\"./%s.hb\")\n\$DEBUG := %s" "$target" "$debug" >"$CONFIG_FILE"
     check_hbc
-
-    case $target in
-    c_native) build_c_native ;;
-    hbvm_ableos) build_hbvm ;;
-    *) die "Invalid target: $target" ;;
-    esac
-
+    build
 }
 
 main "$@"
