documenting some compiler bugs with `(compiler) bug:` tag. see main.hb for vague details
also make build script install hbc for you

diff --git a/build b/build
--- a/build
+++ b/build
@@ -2,13 +2,13 @@
 set -eu
 
 build_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
-
+check_for_update=0
 linker=""
 target="c_native"
 run=0
 out="$build_dir/target/lily"
 
-make_build_dir(){
+make_build_dir() {
     if ! [ -e "$build_dir/target/build" ]; then
         mkdir -p "$build_dir/target/build"
     elif ! [ -w "$build_dir/target/build" ]; then
@@ -17,21 +17,60 @@ make_build_dir(){
     fi
 }
 
-check_out_dir(){
+check_hbc() {
+    has_hbc=1
+    if ! command -v hbc >/dev/null 2>&1; then
+        printf "Warning: hblang compiler not found in \$PATH\n"
+        has_hbc=0
+    fi
+    if command -v cargo >/dev/null 2>&1; then
+        cargo_output=$(cargo install --list | grep 'holey-bytes#' | awk -F'#' '{print substr($2, 1, 8)}')
+
+        if [ -z "$cargo_output" ] && [ $has_hbc = 0 ]; then
+            printf "Note: Installing hblang compiler using cargo\n"
+            if ! cargo +nightly install --git https://git.ablecorp.us/ableos/holey-bytes hbc >/dev/null 2>&1; then
+                printf "Failed to install hblang compiler for whatever reason\n"
+                exit 1
+            fi
+            printf "Done installing\n"
+            return
+        fi
+        if [ $check_for_update = 1 ]; then
+            short_commit_hash=""
+            response=$(curl -s "https://git.ablecorp.us/api/v1/repos/ableos/holey-bytes/commits?limit=1")
+            if [ -n "$response" ]; then
+                commit_hash=$(printf '%s' "$response" | jq -r '.[0].sha' 2>/dev/null)
+                if [ -n "$commit_hash" ] && [ ! "$commit_hash" = "null" ]; then
+                    short_commit_hash="$(printf '%s' "$commit_hash" | cut -c 1-8)"
+                fi
+            fi
+            if [ -n "$short_commit_hash" ]; then
+                if [ ! "$short_commit_hash" = "$cargo_output" ] && [ $has_hbc = 1 ]; then
+                    printf "hblang compiler is out of date"
+                fi
+            fi
+        fi
+    elif [ $has_hbc = 0 ]; then
+        printf "Error: hblang compiler is missing, and could not use cargo to install hblang compiler."
+        exit 1
+    fi
+}
+
+check_out_dir() {
     if ! [ -w "$(dirname "${out}")" ]; then
         printf "ERROR: Out directory does not exist or is not writeable"
         exit 1
     fi
 }
 
-set_target(){
-    echo "target := @use(\"./$target.hb\")" > "$build_dir/src/lib/target/target.hb"
+set_target() {
+    echo "target := @use(\"./$target.hb\")" >"$build_dir/src/lib/target/target.hb"
 }
 
-while :; do 
+while :; do
     case ${1:-""} in
-        -h|--help)
-            printf "build script
+    -h | --help)
+        printf "build script
     -r/--run: run (Available only on target=c_native)
     -l/--linker: set linker (Available only on target=c_native)
     -t/--target: set target (One of: c_native, hbvm_ableos)
@@ -40,68 +79,69 @@ while :; do
 examples
     ./build -t hbvm_ableos
     ./build -r -l 'zig cc' -t c_native"
-            exit
+        exit
         ;;
-        -r|--run)
-            run=1
+    -r | --run)
+        run=1
         ;;
-        -t|--target)
-            if [ -n "${2:-}" ]; then
-                target="${2:-}"
-                shift
-            else
-                printf "ERROR: '--target' requires a non-empty option argument." >&2
-                exit 1
-            fi
-        ;;
-        --target=?*)
-            target=${1#*=}
-        ;;
-        --target=)
-            printf 'ERROR: "--target" requires a non-empty option argument.\n' >&2
-            exit 1
-        ;;
-        -l|--linker)
-            if [ -n "${2:-}" ]; then
-                linker="${2:-}"
-                shift
-            else
-                printf "ERROR: '--linker' requires a non-empty option argument." >&2
-                exit 1
-            fi
-        ;;
-        --linker=?*)
-            linker=${1#*=}
-        ;;
-        --linker=)
-            printf 'ERROR: "--linker" requires a non-empty option argument.\n' >&2
-            exit 1
-        ;;
-        -o|--out)
-            if [ -n "${2:-}" ]; then
-                out="${2:-}"
-                shift
-            else
-                printf "ERROR: '--out' requires a non-empty option argument." >&2
-                exit 1
-            fi
-        ;;
-        --out=?*)
-            out=${1#*=}
-        ;;
-        --out=)
-            printf 'ERROR: "--out" requires a non-empty option argument.\n' >&2
-            exit 1
-        ;;
-        --)
+    -t | --target)
+        if [ -n "${2:-}" ]; then
+            target="${2:-}"
             shift
-            break
+        else
+            printf "ERROR: '--target' requires a non-empty option argument." >&2
+            exit 1
+        fi
         ;;
-        -?*)
-            printf "ERROR: Unknown option %s\n" "$1" >&2
+    --target=?*)
+        target=${1#*=}
         ;;
-        *)
-            break
+    --target=)
+        printf 'ERROR: "--target" requires a non-empty option argument.\n' >&2
+        exit 1
+        ;;
+    -l | --linker)
+        if [ -n "${2:-}" ]; then
+            linker="${2:-}"
+            shift
+        else
+            printf "ERROR: '--linker' requires a non-empty option argument." >&2
+            exit 1
+        fi
+        ;;
+    --linker=?*)
+        linker=${1#*=}
+        ;;
+    --linker=)
+        printf 'ERROR: "--linker" requires a non-empty option argument.\n' >&2
+        exit 1
+        ;;
+    -o | --out)
+        if [ -n "${2:-}" ]; then
+            out="${2:-}"
+            shift
+        else
+            printf "ERROR: '--out' requires a non-empty option argument." >&2
+            exit 1
+        fi
+        ;;
+    --out=?*)
+        out=${1#*=}
+        ;;
+    --out=)
+        printf 'ERROR: "--out" requires a non-empty option argument.\n' >&2
+        exit 1
+        ;;
+    --)
+        shift
+        break
+        ;;
+    -?*)
+        printf "ERROR: Unknown option %s\n" "$1" >&2
+        ;;
+    *)
+        break
+        ;;
     esac
     shift
 done
@@ -115,18 +155,14 @@ if [ $run = 1 ] && [ "$target" = "hbvm_ableos" ]; then
     exit 1
 fi
 
-if ! command -v hbc > /dev/null 2>&1; then
-    printf "Error: hblang compiler not found. Install it with:
-cargo +nightly install --git https://git.ablecorp.us/ableos/holey-bytes hbc --force" >&2
-    exit 1
-fi
+check_hbc
 
 if [ "$target" = "c_native" ]; then
     if [ -z "$linker" ]; then
         set -- "zig cc" "clang" "gcc"
-        for linker; do 
+        for linker; do
             cmd=$(echo "$linker" | awk '{print $1}')
-            if command -v "$cmd" > /dev/null 2>&1; then break; fi
+            if command -v "$cmd" >/dev/null 2>&1; then break; fi
         done
 
         if [ -z "$linker" ]; then
@@ -139,9 +175,9 @@ if [ "$target" = "c_native" ]; then
     check_out_dir
     set_target
 
-    if hbc "$build_dir/src/main.hb" --backend-flags=opt_level=speed > "$build_dir/target/build/lily.o"; then
+    if hbc "$build_dir/src/main.hb" --backend-flags=opt_level=speed >"$build_dir/target/build/lily.o"; then
         $linker "$build_dir/target/build/lily.o" -o "$out"
-        strip -s "$build_dir/target/lily"
+        strip -s "$out"
     else
         echo "compilation failed :(" >&2
         exit 1
@@ -154,7 +190,7 @@ elif [ "$target" = "hbvm_ableos" ]; then
     check_out_dir
     set_target
     if [ "$out" = "$build_dir/target/lily" ]; then out="$build_dir/target/lily.hbf"; fi
-    if ! hbc "$build_dir/src/main.hb" --target=unknown-virt-unknown > "$out"; then
+    if ! hbc "$build_dir/src/main.hb" --target=unknown-virt-unknown >"$out"; then
         echo "compilation failed :(" >&2
         exit 1
     fi
